# Generated by Django 6.0.3 on 2026-04-05 22:35

from django.db import migrations
from decimal import Decimal

def convert_valores(apps, schema_editor):
    Transacao = apps.get_model('finance', 'Transacao')
    for t in Transacao.objects.all():
       if isinstance(t.valor, str):
           try:
               t.valor = Decimal(t.valor.replace(',', '.'))
               t.save()
           except Exception as e:
               t.valor = Decimal('0')
               t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_valores),
    ]
