# Imagem base do Python
FROM python:3.11-slim

# Evita criação de arquivos .pyc
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Pasta de trabalho dentro do container
WORKDIR /app

# Dependências do sistema
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Copia e instala dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código para o container
COPY . .

# Comando padrão
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
